---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
    - name: liveness
      image: k8s.gcr.io/busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 15
        failureThreshold: 1
        periodSeconds: 5
      #      livenessProbe:
      #        tcpSocket:
      #          port: 8080
      #        initialDelaySeconds: 15
      #        periodSeconds: 5
      #      livenessProbe:
      #        grpc:
      #          port: 2379
      #        initialDelaySeconds: 10
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5

